version: '2'
services:
  php:
    image: sjoerd/apache-php7
    volumes:
      - ./:/var/www/html
    ports:
      - '8000:80'
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: kampacties
      MYSQL_DATABASE: kampacties
      MYSQL_USER: kampacties
      MYSQL_PASSWORD: kampacties
